# -*- coding: utf-8 -*-
"""Metadata webu — pořadí okruhů podle osnovy, popisky a podtémata pro dlaždice.

Každý text menu má vedle české verze i anglickou a slovenskou (pole *_en a *_sk,
u podtémat chips_en a chips_sk ve stejném pořadí). Menu webu je trojjazyčné (nabídka
CZ/SK/EN); chybějící překlad zastaví make_site.py i kontrolu `python i18n.py --check`.
Viz CLAUDE.md. Angličtina je britská (colour, practise), slovenčina spisovná.
"""

SITE = {
    "name": "Chemie",
    "name_en": "Chemistry",
    "name_sk": "Chémia",
    "tagline": "Interaktivní studijní materiály z chemie",
    "tagline_en": "Interactive chemistry study materials",
    "tagline_sk": "Interaktívne študijné materiály z chémie",
    "lead": "Interaktivní materiály k chemii: výklad, modely, na kterých si věci osaháte, "
            "řešené příklady krok za krokem a testy, které u každé otázky vysvětlí, "
            "proč je odpověď správná.",
    "lead_en": "Interactive chemistry materials: explanations, models you can get hands-on with, "
               "worked examples step by step, and tests that explain for every question "
               "why the answer is right.",
    "lead_sk": "Interaktívne materiály z chémie: výklad, modely, na ktorých si veci vyskúšate sami, riešené príklady krok za krokom a testy, ktoré pri každej otázke vysvetlia, prečo je odpoveď správna.",
    "group_lead": "Deset okruhů v pořadí podle školní osnovy. Každý je samostatná stránka s rychlokurzem, "
                  "plným kurzem, testy, tahákem a slovníčkem pojmů.",
    "group_lead_en": "Ten topics in the order of the school syllabus. Each is a separate page with "
                     "a crash course, a full course, tests, a cheat sheet and a glossary.",
    "group_lead_sk": "Desať okruhov v poradí podľa školských osnov. Každý je samostatná stránka s rýchlokurzom, plným kurzom, testami, ťahákom a slovníčkom pojmov.",
}

GROUPS = [
    {
        "id": "okruhy", "slug": "obecna-fyzikalni-chemie",
        "title": "Obecná a fyzikální chemie",
        "title_en": "General and physical chemistry",
        "title_sk": "Všeobecná a fyzikálna chémia",
        "sub": "Deset okruhů podle školní osnovy. Výklad, interaktivní modely, "
               "řešené příklady a testy s vysvětlením u každé otázky.",
        "sub_en": "Ten topics following the school syllabus. Explanations, interactive models, "
                  "worked examples and tests with an explanation for every question.",
        "sub_sk": "Desať okruhov podľa školských osnov. Výklad, interaktívne modely, riešené príklady a testy s vysvetlením pri každej otázke.",
        "kicker": "Naučit se", "kicker_en": "Learn",
        "kicker_sk": "Naučiť sa",
        "cta": "Zobrazit okruhy", "cta_en": "Show topics",
        "cta_sk": "Zobraziť okruhy",
        "state": "ready", "icon": "okruhy",
    },
    {
        "id": "anorganika", "slug": "anorganicka-chemie",
        "title": "Anorganická chemie",
        "title_en": "Inorganic chemistry",
        "title_sk": "Anorganická chémia",
        "sub": "Popisná chemie prvků a jejich sloučenin: co existuje, jak to vzniká, "
               "jak se to chová a proč — od vodíku po přechodné kovy.",
        "sub_en": "Descriptive chemistry of the elements and their compounds: what exists, "
                  "how it forms, how it behaves and why — from hydrogen to the transition metals.",
        "sub_sk": "Opisná chémia prvkov a ich zlúčenín: čo existuje, ako to vzniká, ako sa to správa a prečo — od vodíka po prechodné kovy.",
        "kicker": "Naučit se", "kicker_en": "Learn",
        "kicker_sk": "Naučiť sa",
        "cta": "Zobrazit okruhy", "cta_en": "Show topics",
        "cta_sk": "Zobraziť okruhy",
        "state": "ready", "icon": "anorganika",
    },
    {
        "id": "testy", "slug": "testy-nanecisto",
        "title": "Testy nanečisto",
        "title_en": "Mock tests",
        "title_sk": "Testy nanečisto",
        "sub": "Souhrnné testy napříč okruhy: na čas, bez nápovědy a s rozborem, "
               "který okruh vás srazil nejvíc.",
        "sub_en": "Summary tests across topics: timed, without hints, and with a breakdown "
                  "of which topic cost you the most points.",
        "sub_sk": "Súhrnné testy naprieč okruhmi: na čas, bez nápovedy a s rozborom, ktorý okruh vám dal najviac zabrať.",
        "kicker": "Vyzkoušet se", "kicker_en": "Test yourself",
        "kicker_sk": "Vyskúšať sa",
        "cta": "Vybrat test", "cta_en": "Choose a test",
        "cta_sk": "Vybrať test",
        "state": "ready", "icon": "test",
    },
    {
        "id": "pocitani", "slug": "pocitani",
        "title": "Počítání",
        "title_en": "Calculating",
        "title_sk": "Počítanie",
        "sub": "Jak výpočet zapsat, jak zacházet se zlomky a závorkami a jak si ho "
               "natrénovat na úlohách. Tři moduly, které na sebe navazují.",
        "sub_en": "How to write a calculation down, how to handle fractions and brackets, "
                  "and how to practise it on problems. Three modules that build on each other.",
        "sub_sk": "Ako výpočet zapísať, ako zaobchádzať so zlomkami a zátvorkami a ako si ho natrénovať na úlohách. Tri moduly, ktoré na seba nadväzujú.",
        "kicker": "Naučit se", "kicker_en": "Learn",
        "kicker_sk": "Naučiť sa",
        "cta": "Zobrazit moduly", "cta_en": "Show modules",
        "cta_sk": "Zobraziť moduly",
        "state": "ready", "icon": "pocty",
    },
    {
        "id": "zlomky", "slug": "jak-pocitat/zlomky-a-zavorky",
        "title": "Zlomky a závorky",
        "title_en": "Fractions and brackets",
        "title_sk": "Zlomky a zátvorky",
        "sub": "Kdy zlomková čára nahrazuje závorku, jak přepsat stohovaný zápis "
               "na řádek a zpátky a jak si ověřit, že jste přepsali správně.",
        "sub_en": "When the fraction bar replaces brackets, how to rewrite stacked notation "
                  "on one line and back, and how to check that you rewrote it correctly.",
        "sub_sk": "Kedy zlomková čiara nahrádza zátvorku, ako prepísať poschodový zápis do jedného riadku a späť a ako si overiť, že ste prepísali správne.",
        "kicker": "Doladit si", "kicker_en": "Fine-tune",
        "kicker_sk": "Doladiť si",
        "cta": "Otevřít modul", "cta_en": "Open module",
        "cta_sk": "Otvoriť modul",
        "state": "ready", "icon": "zlomky",
    },
    {
        "id": "pocitat", "slug": "jak-pocitat",
        "title": "Jak počítat chemii",
        "title_en": "How to do chemistry calculations",
        "title_sk": "Ako počítať chémiu",
        "sub": "Jak zapsat zadání, odvodit vztah a teprve pak dosadit. "
               "Jednotky, převody, přehled vzorců a řešené příklady.",
        "sub_en": "How to write down what is given, derive the relationship and only then "
                  "substitute. Units, conversions, an overview of formulas and worked examples.",
        "sub_sk": "Ako zapísať zadanie, odvodiť vzťah a až potom dosadiť. Jednotky, prevody, prehľad vzorcov a riešené príklady.",
        "kicker": "Naučit se", "kicker_en": "Learn",
        "kicker_sk": "Naučiť sa",
        "cta": "Naučit se zápis", "cta_en": "Learn the notation",
        "cta_sk": "Naučiť sa zápis",
        "state": "ready", "icon": "pocty",
    },
    {
        "id": "spolu", "slug": "pocitame-spolu",
        "title": "Počítáme spolu",
        "title_en": "Let’s calculate together",
        "title_sk": "Počítame spolu",
        "sub": "Výpočet skládáte vy: vyberete vztahy, klepáním dosadíte jeden do druhého "
               "a čísla přijdou na řadu až úplně nakonec.",
        "sub_en": "You build the calculation: pick the relationships, tap to substitute one "
                  "into another, and the numbers come in only at the very end.",
        "sub_sk": "Výpočet skladáte vy: vyberiete vzťahy, ťuknutím dosadíte jeden do druhého a čísla prídu na rad až úplne na konci.",
        "kicker": "Procvičit si", "kicker_en": "Practise",
        "kicker_sk": "Precvičiť si",
        "cta": "Začít počítat", "cta_en": "Start calculating",
        "cta_sk": "Začať počítať",
        "state": "ready", "icon": "spolu",
    },
    {
        "id": "tabulka", "slug": "periodicka-tabulka",
        "title": "Periodická tabulka",
        "title_en": "Periodic table",
        "title_sk": "Periodická tabuľka",
        "sub": "Všech 118 prvků s daty a šesti režimy obarvení, výklad period, skupin a bloků, "
               "a počítadlo molární hmotnosti ze vzorce včetně hydrátů a složených závorek.",
        "sub_en": "All 118 elements with data and six colouring modes, an explanation of periods, "
                  "groups and blocks, and a molar mass calculator that works from a formula, "
                  "including hydrates and nested brackets.",
        "sub_sk": "Všetkých 118 prvkov s údajmi a šiestimi režimami farbenia, výklad periód, skupín a blokov a kalkulačka molárnej hmotnosti zo vzorca vrátane hydrátov a zložených zátvoriek.",
        "kicker": "Mít po ruce", "kicker_en": "Keep at hand",
        "kicker_sk": "Mať po ruke",
        "cta": "Otevřít tabulku", "cta_en": "Open the table",
        "cta_sk": "Otvoriť tabuľku",
        "state": "ready", "icon": "tabulka",
    },
    {
        "id": "nazvoslovi", "slug": "nazvoslovi",
        "title": "České názvosloví",
        "title_en": "Czech nomenclature",
        "title_sk": "České názvoslovie",
        "sub": "Trenažér názvů a vzorců oběma směry. Osm tříd sloučenin, "
               "úlohy se generují a u každé odpovědi je rozbor, proč to tak je.",
        "sub_en": "A trainer for names and formulas in both directions. Eight classes of compounds, "
                  "generated exercises and an explanation of why for every answer.",
        "sub_sk": "Trenažér názvov a vzorcov oboma smermi. Osem tried zlúčenín, úlohy sa generujú a pri každej odpovedi je rozbor, prečo to tak je.",
        "kicker": "Nadrilovat si", "kicker_en": "Drill",
        "kicker_sk": "Nadrilovať si",
        "cta": "Začít trénovat", "cta_en": "Start training",
        "cta_sk": "Začať trénovať",
        "state": "ready", "icon": "nazvo",
    },
    {
        "id": "prikladu", "slug": None,
        "title": "Sbírka příkladů",
        "title_en": "Problem collection",
        "title_sk": "Zbierka príkladov",
        "sub": "Početní úlohy k procvičení, řazené podle obtížnosti.",
        "sub_en": "Calculation problems for practice, sorted by difficulty.",
        "sub_sk": "Výpočtové úlohy na precvičenie, zoradené podľa náročnosti.",
        "kicker": "Chystá se", "kicker_en": "In preparation",
        "kicker_sk": "Chystá sa",
        "cta": "Zatím není hotové", "cta_en": "Not ready yet",
        "cta_sk": "Zatiaľ nie je hotové",
        "state": "soon", "icon": "priklady",
    },
]

# dvojice na úvodní stránce — co spolu souvisí, stojí vedle sebe
PAIRS = [
    {"label": "Látka", "label_en": "Theory",
     "label_sk": "Učivo",
     "note": "Nejdřív obecné zákonitosti, pak popisná chemie prvků a jejich sloučenin.",
     "note_en": "First the general principles, then the descriptive chemistry of the elements "
                "and their compounds.",
     "note_sk": "Najprv všeobecné zákonitosti, potom opisná chémia prvkov a ich zlúčenín.",
     "items": ["okruhy", "anorganika"]},
    {"label": "Výpočty", "label_en": "Calculations",
     "label_sk": "Výpočty",
     "note": "Jak výpočet zapsat — a tabulka, kterou u toho máte po ruce.",
     "note_en": "How to write a calculation down — and the table to keep at hand while you do.",
     "note_sk": "Ako výpočet zapísať — a tabuľka, ktorú pri tom máte po ruke.",
     "items": ["pocitani", "tabulka"], "flow": False},
    {"label": "Procvičení", "label_en": "Practice",
     "label_sk": "Precvičovanie",
     "note": "Vyzkoušejte se nanečisto na čas, nebo si projděte početní úlohy.",
     "note_en": "Take a timed mock test, or work through calculation problems.",
     "note_sk": "Vyskúšajte sa nanečisto na čas alebo si prejdite výpočtové úlohy.",
     "items": ["testy", "nazvoslovi", "prikladu"], "flow": False},
]

# pořadí přesně podle osnovy učitele
TOPICS = [
    {
        "slug": "atomove-jadro",
        "n": "01",
        "title": "Atomové jádro, přeměny jader a radioaktivita",
        "title_en": "The atomic nucleus, nuclear transformations and radioactivity",
        "title_sk": "Atómové jadro, premeny jadier a rádioaktivita",
        "sub": "Z čeho se skládá jádro, proč se některá jádra rozpadají a jak rychle.",
        "sub_en": "What the nucleus is made of, why some nuclei decay, and how fast.",
        "sub_sk": "Z čoho sa skladá jadro, prečo sa niektoré jadrá rozpadajú a ako rýchlo.",
        "chips": ["protonové a nukleonové číslo", "izotopy, izobary, izotony",
                  "řeka stability", "přeměny α, β, γ", "ionizující záření", "rozpadový zákon"],
        "chips_en": ["proton and nucleon number", "isotopes, isobars, isotones",
                     "band of stability", "α, β and γ decay", "ionising radiation",
                     "radioactive decay law"],
        "chips_sk": ["protónové a nukleónové číslo", "izotopy, izobary, izotóny", "pás stability", "premeny α, β, γ", "ionizujúce žiarenie", "zákon rádioaktívneho rozpadu"],
    },
    {
        "slug": "elektronovy-obal",
        "n": "02",
        "title": "Elektronový obal a periodická tabulka",
        "title_en": "Electron shells and the periodic table",
        "title_sk": "Elektrónový obal a periodická tabuľka",
        "sub": "Od pudinkového modelu ke kvantové mechanice a k tomu, proč tabulka vypadá, jak vypadá.",
        "sub_en": "From the plum pudding model to quantum mechanics, and why the periodic table "
                  "looks the way it does.",
        "sub_sk": "Od pudingového modelu ku kvantovej mechanike a k tomu, prečo tabuľka vyzerá tak, ako vyzerá.",
        "chips": ["modely atomu", "orbital", "kvantová čísla", "spin",
                  "elektronová konfigurace", "ionizační energie", "elektronegativita"],
        "chips_en": ["models of the atom", "orbital", "quantum numbers", "spin",
                     "electron configuration", "ionisation energy", "electronegativity"],
        "chips_sk": ["modely atómu", "orbitál", "kvantové čísla", "spin", "elektrónová konfigurácia", "ionizačná energia", "elektronegativita"],
    },
    {
        "slug": "chemicka-vazba",
        "n": "03",
        "title": "Chemická vazba",
        "title_en": "Chemical bonding",
        "title_sk": "Chemická väzba",
        "sub": "Kovová, iontová, kovalentní a slabé interakce — a co z nich plyne pro vlastnosti látek.",
        "sub_en": "Metallic, ionic and covalent bonds and weak interactions — and what they mean "
                  "for the properties of substances.",
        "sub_sk": "Kovová, iónová a kovalentná väzba a slabé interakcie — a čo z nich vyplýva pre vlastnosti látok.",
        "chips": ["kovová vazba", "iontová vazba", "kovalentní vazba", "σ a π",
                  "polarita", "koordinační vazba", "vodíkové můstky"],
        "chips_en": ["metallic bond", "ionic bond", "covalent bond", "σ and π",
                     "polarity", "coordinate bond", "hydrogen bonds"],
        "chips_sk": ["kovová väzba", "iónová väzba", "kovalentná väzba", "σ a π", "polarita", "koordinačná väzba", "vodíkové mostíky"],
    },
    {
        "slug": "struktura-latek",
        "n": "04",
        "title": "Chemická struktura a vlastnosti látek",
        "title_en": "Chemical structure and properties of substances",
        "title_sk": "Chemická štruktúra a vlastnosti látok",
        "sub": "Jak uspořádání částic rozhoduje o tom, co látka dělá.",
        "sub_en": "How the arrangement of particles decides what a substance does.",
        "sub_sk": "Ako usporiadanie častíc rozhoduje o tom, čo látka robí.",
        "chips": ["pevné látky, kapaliny, plyny", "krystalová mřížka", "amorfní stav",
                  "teorie VSEPR", "hybridizace", "rozpustnost a mísitelnost"],
        "chips_en": ["solids, liquids, gases", "crystal lattice", "amorphous state",
                     "VSEPR theory", "hybridisation", "solubility and miscibility"],
        "chips_sk": ["pevné látky, kvapaliny, plyny", "kryštálová mriežka", "amorfný stav", "teória VSEPR", "hybridizácia", "rozpustnosť a miešateľnosť"],
    },
    {
        "slug": "termochemie",
        "n": "05",
        "title": "Termochemie a úvod do termodynamiky",
        "title_en": "Thermochemistry and an introduction to thermodynamics",
        "title_sk": "Termochémia a úvod do termodynamiky",
        "sub": "Proč některé reakce hřejí, jiné studí — a proč některé samy od sebe neproběhnou.",
        "sub_en": "Why some reactions give off heat and others take it in — and why some "
                  "do not happen on their own.",
        "sub_sk": "Prečo niektoré reakcie hrejú, iné chladia — a prečo niektoré samy od seba neprebehnú.",
        "chips": ["1. termodynamický zákon", "enthalpie", "Hessův zákon",
                  "exo a endo", "entropie", "Gibbsova energie"],
        "chips_en": ["first law of thermodynamics", "enthalpy", "Hess’s law",
                     "exo and endo", "entropy", "Gibbs energy"],
        "chips_sk": ["1. termodynamický zákon", "entalpia", "Hessov zákon", "exo a endo", "entropia", "Gibbsova energia"],
    },
    {
        "slug": "chemicka-kinetika",
        "n": "06",
        "title": "Chemická kinetika",
        "title_en": "Chemical kinetics",
        "title_sk": "Chemická kinetika",
        "sub": "Termodynamika řekla jestli, kinetika odpoví jak rychle.",
        "sub_en": "Thermodynamics tells you whether, kinetics tells you how fast.",
        "sub_sk": "Termodynamika povedala či, kinetika odpovie, ako rýchlo.",
        "chips": ["rychlost reakce", "rychlostní rovnice", "řád a molekularita",
                  "srážková teorie", "aktivovaný komplex", "katalýza"],
        "chips_en": ["reaction rate", "rate equation", "order and molecularity",
                     "collision theory", "activated complex", "catalysis"],
        "chips_sk": ["rýchlosť reakcie", "rýchlostná rovnica", "poriadok a molekulovosť", "zrážková teória", "aktivovaný komplex", "katalýza"],
    },
    {
        "slug": "chemicka-rovnovaha",
        "n": "07",
        "title": "Chemická rovnováha",
        "title_en": "Chemical equilibrium",
        "title_sk": "Chemická rovnováha",
        "sub": "Když obě reakce běží stejně rychle a navenek se nic neděje.",
        "sub_en": "When both reactions run equally fast and nothing seems to happen.",
        "sub_sk": "Keď obe reakcie bežia rovnako rýchlo a navonok sa nič nedeje.",
        "chips": ["dynamická rovnováha", "rovnovážná konstanta", "Guldberg–Waage",
                  "stupeň konverze", "vliv teploty a tlaku", "Le Chatelier"],
        "chips_en": ["dynamic equilibrium", "equilibrium constant", "Guldberg–Waage",
                     "degree of conversion", "effect of temperature and pressure", "Le Chatelier"],
        "chips_sk": ["dynamická rovnováha", "rovnovážna konštanta", "Guldberg–Waage", "stupeň konverzie", "vplyv teploty a tlaku", "Le Chatelier"],
    },
    {
        "slug": "elektrochemie",
        "n": "08",
        "title": "Rovnovážná elektrochemie",
        "title_en": "Equilibrium electrochemistry",
        "title_sk": "Rovnovážna elektrochémia",
        "sub": "Redoxní reakce, články a elektrolýza — chemie, která tlačí elektrony.",
        "sub_en": "Redox reactions, cells and electrolysis — chemistry that pushes electrons around.",
        "sub_sk": "Redoxné reakcie, články a elektrolýza — chémia, ktorá posúva elektróny.",
        "chips": ["oxidace a redukce", "redukční potenciál", "Beketovova řada",
                  "Nernstova rovnice", "katoda a anoda", "elektrolýza", "koroze"],
        "chips_en": ["oxidation and reduction", "reduction potential", "reactivity series of metals",
                     "Nernst equation", "cathode and anode", "electrolysis", "corrosion"],
        "chips_sk": ["oxidácia a redukcia", "redukčný potenciál", "Beketovov rad", "Nernstova rovnica", "katóda a anóda", "elektrolýza", "korózia"],
    },
    {
        "slug": "acidobazicke-reakce",
        "n": "09",
        "title": "Acidobazické reakce",
        "title_en": "Acid–base reactions",
        "title_sk": "Acidobázické reakcie",
        "sub": "Tři teorie kyselin a zásad a jak podle nich předpovědět, co se stane.",
        "sub_en": "Three theories of acids and bases, and how to use them to predict what will happen.",
        "sub_sk": "Tri teórie kyselín a zásad a ako podľa nich predpovedať, čo sa stane.",
        "chips": ["Arrhenius, Brønsted, Lewis", "konjugovaný pár", "síla kyselin",
                  "konstanta acidity", "předpovídání reakcí", "hydrolýza solí"],
        "chips_en": ["Arrhenius, Brønsted, Lewis", "conjugate pair", "acid strength",
                     "acidity constant", "predicting reactions", "salt hydrolysis"],
        "chips_sk": ["Arrhenius, Brønsted, Lewis", "konjugovaný pár", "sila kyselín", "konštanta acidity", "predpovedanie reakcií", "hydrolýza solí"],
    },
    {
        "slug": "vypocty-rovnovah",
        "n": "10",
        "title": "Výpočty související s chemickou rovnováhou",
        "title_en": "Calculations related to chemical equilibrium",
        "title_sk": "Výpočty súvisiace s chemickou rovnováhou",
        "sub": "Počítání pH, srážení a komplexů — nejvíc bodů na přijímačkách.",
        "sub_en": "Calculating pH, precipitation and complexes — the most points in entrance exams.",
        "sub_sk": "Počítanie pH, zrážania a komplexov — najviac bodov na prijímačkách.",
        "chips": ["pH silných kyselin a bází", "slabé kyseliny a báze", "soli",
                  "pufry", "srážecí rovnováhy", "komplexotvorné rovnováhy"],
        "chips_en": ["pH of strong acids and bases", "weak acids and bases", "salts",
                     "buffers", "precipitation equilibria", "complex formation equilibria"],
        "chips_sk": ["pH silných kyselín a zásad", "slabé kyseliny a zásady", "soli", "tlmivé roztoky", "zrážacie rovnováhy", "komplexotvorné rovnováhy"],
    },
]

# localStorage prefixy jednotlivých průvodců (kvůli sjednocení světlého/tmavého režimu)
PREFIXES = ["termo", "jadro", "obal", "vazba", "struktura",
            "kinetika", "rovnovaha", "elchem", "acidobaze", "vypocty"]

# ---- Anorganická chemie -------------------------------------------------
# Pořadí i členění sleduje učebnici Klikorka J., Hájek B., Votinský J.:
# Obecná a anorganická chemie, 2. vydání, SNTL, Praha 1989. Výklad je vlastní.
ANORG_TOPICS = [
    {
        "slug": "vodik-a-voda", "n": "01",
        "title": "Vodík a voda",
        "title_en": "Hydrogen and water",
        "title_sk": "Vodík a voda",
        "sub": "Nejjednodušší prvek, který se nevejde do žádné skupiny — a nejdůležitější sloučenina, kterou tvoří.",
        "sub_en": "The simplest element, which fits into no group — and the most important "
                  "compound it forms.",
        "sub_sk": "Najjednoduchší prvok, ktorý sa nezmestí do žiadnej skupiny — a najdôležitejšia zlúčenina, ktorú tvorí.",
        "chips": ["postavení vodíku", "izotopy", "hydridy", "výroba a použití",
                  "struktura vody", "vodíkové můstky", "tvrdost vody", "peroxid vodíku"],
        "chips_en": ["position of hydrogen", "isotopes", "hydrides", "production and uses",
                     "structure of water", "hydrogen bonds", "water hardness", "hydrogen peroxide"],
        "chips_sk": ["postavenie vodíka", "izotopy", "hydridy", "výroba a použitie", "štruktúra vody", "vodíkové mostíky", "tvrdosť vody", "peroxid vodíka"],
    },
    {
        "slug": "halogeny-a-vzacne-plyny", "n": "02",
        "title": "Halogeny a vzácné plyny",
        "title_en": "Halogens and noble gases",
        "title_sk": "Halogény a vzácne plyny",
        "sub": "Skupina 17 a 18: nejreaktivnější nekovy vedle prvků, které dlouho platily za netečné.",
        "sub_en": "Groups 17 and 18: the most reactive non-metals next to elements that were "
                  "long thought to be inert.",
        "sub_sk": "Skupina 17 a 18: najreaktívnejšie nekovy vedľa prvkov, ktoré dlho platili za netečné.",
        "chips": ["trendy ve skupině 17", "halogenovodíky", "kyslíkaté kyseliny halogenů",
                  "výroba chloru", "fluor a jeho zvláštnosti", "sloučeniny xenonu", "využití"],
        "chips_en": ["trends in group 17", "hydrogen halides", "halogen oxoacids",
                     "chlorine production", "fluorine and its peculiarities", "xenon compounds", "uses"],
        "chips_sk": ["trendy v 17. skupine", "halogenovodíky", "kyslíkaté kyseliny halogénov", "výroba chlóru", "fluór a jeho zvláštnosti", "zlúčeniny xenónu", "využitie"],
    },
    {
        "slug": "kyslik-a-chalkogeny", "n": "03",
        "title": "Kyslík a chalkogeny",
        "title_en": "Oxygen and the chalcogens",
        "title_sk": "Kyslík a chalkogény",
        "sub": "Skupina 16: kyslík a ozon, síra a její oxokyseliny, přechod od nekovu ke kovu.",
        "sub_en": "Group 16: oxygen and ozone, sulfur and its oxoacids, the shift from non-metal to metal.",
        "sub_sk": "Skupina 16: kyslík a ozón, síra a jej oxokyseliny, prechod od nekovu ku kovu.",
        "chips": ["modifikace kyslíku", "oxidy a jejich dělení", "ozon",
                  "modifikace síry", "sulfan a sulfidy", "kyselina sírová", "selen a tellur"],
        "chips_en": ["allotropes of oxygen", "oxides and how they are classified", "ozone",
                     "allotropes of sulfur", "hydrogen sulfide and sulfides", "sulfuric acid",
                     "selenium and tellurium"],
        "chips_sk": ["modifikácie kyslíka", "oxidy a ich delenie", "ozón", "modifikácie síry", "sulfán a sulfidy", "kyselina sírová", "selén a telúr"],
    },
    {
        "slug": "dusik-a-fosfor", "n": "04",
        "title": "Dusík a fosfor",
        "title_en": "Nitrogen and phosphorus",
        "title_sk": "Dusík a fosfor",
        "sub": "Skupina 15: od netečného N₂ k výbušninám a hnojivům, a proč se fosfor chová jinak.",
        "sub_en": "Group 15: from inert N₂ to explosives and fertilisers, and why phosphorus "
                  "behaves differently.",
        "sub_sk": "Skupina 15: od netečného N₂ k výbušninám a hnojivám a prečo sa fosfor správa inak.",
        "chips": ["trojná vazba v N₂", "amoniak a Haberův proces", "oxidy dusíku",
                  "kyselina dusičná", "modifikace fosforu", "kyseliny fosforu", "hnojiva"],
        "chips_en": ["the triple bond in N₂", "ammonia and the Haber process", "nitrogen oxides",
                     "nitric acid", "allotropes of phosphorus", "phosphorus acids", "fertilisers"],
        "chips_sk": ["trojitá väzba v N₂", "amoniak a Haberov proces", "oxidy dusíka", "kyselina dusičná", "modifikácie fosforu", "kyseliny fosforu", "hnojivá"],
    },
    {
        "slug": "uhlik-kremik-bor", "n": "05",
        "title": "Uhlík, křemík a bor",
        "title_en": "Carbon, silicon and boron",
        "title_sk": "Uhlík, kremík a bór",
        "sub": "Prvky, které staví kostry: řetězce uhlíku, sítě křemíku a elektronový deficit boru.",
        "sub_en": "Elements that build frameworks: carbon chains, silicon networks and the "
                  "electron deficiency of boron.",
        "sub_sk": "Prvky, ktoré stavajú kostry: reťazce uhlíka, siete kremíka a elektrónový deficit bóru.",
        "chips": ["modifikace uhlíku", "oxidy uhlíku", "uhličitany", "silikáty",
                  "sklo a keramika", "borany a elektronový deficit", "diagonální podobnost"],
        "chips_en": ["allotropes of carbon", "carbon oxides", "carbonates", "silicates",
                     "glass and ceramics", "boranes and electron deficiency", "diagonal relationship"],
        "chips_sk": ["modifikácie uhlíka", "oxidy uhlíka", "uhličitany", "silikáty", "sklo a keramika", "borány a elektrónový deficit", "diagonálna podobnosť"],
    },
    {
        "slug": "elementarni-kovy", "n": "06",
        "title": "Elementární kovy",
        "title_en": "Metals as elements",
        "title_sk": "Elementárne kovy",
        "sub": "Co dělá kov kovem: vazba, mřížka, slitiny a jak se kovy dostávají z rudy.",
        "sub_en": "What makes a metal a metal: bonding, lattice, alloys, and how metals are "
                  "extracted from ore.",
        "sub_sk": "Čo robí kov kovom: väzba, mriežka, zliatiny a ako sa kovy získavajú z rúd.",
        "chips": ["kovová vazba a pásová teorie", "typy mřížek", "slitiny",
                  "metalurgie", "redukce rud", "elektrolytická výroba", "koroze"],
        "chips_en": ["metallic bonding and band theory", "lattice types", "alloys",
                     "metallurgy", "reduction of ores", "electrolytic production", "corrosion"],
        "chips_sk": ["kovová väzba a pásová teória", "typy mriežok", "zliatiny", "metalurgia", "redukcia rúd", "elektrolytická výroba", "korózia"],
    },
    {
        "slug": "neprechodne-kovy", "n": "07",
        "title": "Nepřechodné kovy",
        "title_en": "Main-group metals",
        "title_sk": "Neprechodné kovy",
        "sub": "Kovy bloků s a p: alkalické kovy, kovy alkalických zemin, hliník a efekt inertního páru.",
        "sub_en": "Metals of the s- and p-blocks: alkali metals, alkaline earth metals, aluminium "
                  "and the inert pair effect.",
        "sub_sk": "Kovy blokov s a p: alkalické kovy, kovy alkalických zemín, hliník a efekt inertného páru.",
        "chips": ["alkalické kovy", "kovy alkalických zemin", "hliník a amfoterita",
                  "cín a olovo", "efekt inertního páru", "Solvayův proces", "biogenní prvky"],
        "chips_en": ["alkali metals", "alkaline earth metals", "aluminium and amphoterism",
                     "tin and lead", "inert pair effect", "Solvay process", "biogenic elements"],
        "chips_sk": ["alkalické kovy", "kovy alkalických zemín", "hliník a amfotérnosť", "cín a olovo", "efekt inertného páru", "Solvayov proces", "biogénne prvky"],
    },
    {
        "slug": "koordinacni-slouceniny", "n": "08",
        "title": "Koordinační sloučeniny",
        "title_en": "Coordination compounds",
        "title_sk": "Koordinačné zlúčeniny",
        "sub": "Komplexy: centrální atom, ligandy a teorie, které vysvětlí jejich barvu i magnetismus.",
        "sub_en": "Complexes: the central atom, ligands, and the theories that explain their "
                  "colour and magnetism.",
        "sub_sk": "Komplexy: centrálny atóm, ligandy a teórie, ktoré vysvetlia ich farbu aj magnetizmus.",
        "chips": ["centrální atom a ligandy", "koordinační číslo", "názvosloví komplexů",
                  "izomerie", "teorie krystalového pole", "barevnost", "chelatace"],
        "chips_en": ["central atom and ligands", "coordination number", "naming complexes",
                     "isomerism", "crystal field theory", "colour", "chelation"],
        "chips_sk": ["centrálny atóm a ligandy", "koordinačné číslo", "názvoslovie komplexov", "izoméria", "teória kryštálového poľa", "farebnosť", "chelatácia"],
    },
    {
        "slug": "prechodne-kovy", "n": "09",
        "title": "Přechodné kovy",
        "title_en": "Transition metals",
        "title_sk": "Prechodné kovy",
        "sub": "Blok d: proměnlivá oxidační čísla, barevné sloučeniny a kovy, na kterých stojí průmysl.",
        "sub_en": "The d-block: variable oxidation states, coloured compounds and the metals "
                  "that industry is built on.",
        "sub_sk": "Blok d: premenlivé oxidačné čísla, farebné zlúčeniny a kovy, na ktorých stojí priemysel.",
        "chips": ["konfigurace d", "oxidační čísla", "triáda železa", "chrom a mangan",
                  "měď, stříbro, zlato", "zinková skupina", "katalýza", "výroba oceli"],
        "chips_en": ["d configurations", "oxidation states", "the iron triad", "chromium and manganese",
                     "copper, silver, gold", "the zinc group", "catalysis", "steelmaking"],
        "chips_sk": ["konfigurácie d", "oxidačné čísla", "triáda železa", "chróm a mangán", "meď, striebro, zlato", "zinková skupina", "katalýza", "výroba ocele"],
    },
]

ANORG_PREFIXES = ["vodik", "halogeny", "chalkogeny", "dusik", "uhlik",
                  "kovy", "nekovy", "komplexy", "prechodne"]
